version: 2.1
orbs:
  pcs: prisma_cloud/devops_security@3.0.4
  bridgecrew: bridgecrew/bridgecrew@1.0.3
jobs:
  scan_image:
    executor: pcs/compute
    steps:
      - checkout
      - run: 'docker pull nginx:1.17.9-alpine'
      - pcs/scan_image:
          prisma_cloud_compute_url: $prisma_cloud_compute_url
          prisma_cloud_compute_username: $prisma_cloud_access_key
          prisma_cloud_compute_password: prisma_cloud_secret_key
          prisma_cloud_scan_image: nginx:1.17.9-alpine
          reports: csv,junit
  iac_scan:
    executor: bridgecrew/default
    environment:
      PRISMA_API_URL: https://api3.prismacloud.io
    steps:
      - checkout
      - bridgecrew/scan:
          directory: .
          api-key-variable: iac_api_key
workflows:
  scan:
    jobs:
      - scan_image
      - iac_scan
